export default {
  apiUrl:'https://droos.alhutacademy.com/',
  token :`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZHJvb3MuYWxodXRhY2FkZW15LmNvbSIsImlhdCI6MTY1ODQ5MDI1NywibmJmIjoxNjU4NDkwMjU3LCJleHAiOjE2NTkwOTUwNTcsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.xArNTVfzktQFYlIazlU9u0MUYkBrghOeC9f2c7zkdK0`,
}

